### ISSUE TITLE
expecting to support *.asn1 file

### ISSUE THREAD

**Issue by BxJiang** [HuiMi24/TtcnComplete#1]
Hi there, I'm expecting these awesome features working with *.asn1 fils, some guys put ".asn1" suffix rather than ".asn".

**Comment by HuiMi24** [comment]
".asn1" file extension added. But I don't have time to test it. It should work.
I'm very happy you love this plugin. but I'm no longer use TTCN-3 and ASN.1. So, there's no new feature for this plugin.  Anyway, I think this is enough for TTCN-3, enjoy it!
